name: Publish GitHub Pages

on:
  push:
    branches:
      - main
      - master
    tags:
      - v*

permissions: write-all

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          fetch-depth: 1
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup uv
        uses: astral-sh/setup-uv@v7
        with:
          version: "latest"
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Deploy docs
        run: |
          uv sync --group docs
          uv run make gen-docs
          uv run zensical build

      - name: Setup Pages
        uses: actions/configure-pages@v6

      - name: Delete stale github-pages artifact from previous attempts
        uses: geekyeggo/delete-artifact@v5
        with:
          name: github-pages
          failOnError: false

      - name: Upload to GitHub Pages
        uses: actions/upload-pages-artifact@v4
        with:
          path: ./site

      - name: Publish to GitHub Pages
        uses: actions/deploy-pages@v4
